config/routes.rb
Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  root to: 'visitors#index'
  devise_for :users
  resources :hosts, :activities, :locations
  resources :users do
    member do 
      get 'my_appointments'
    end
  end
  resources :events do 
    member do
      get 'confirm_delete'
      get 'new_schedule_block'
      post 'create_schedule_block'
      get 'show_schedule_block'
      get 'edit_schedule_block'
      post 'update_schedule_block'
      get 'block_schedule_block'
      post 'create_appointment'
    end
    collection do
      get 'index_schedule_block'
    end
  end

end

app/models/event.rb
# == Schema Information
#
# Table name: events
#
#  id          :integer          not null, primary key
#  activity_id :integer
#  host_id     :integer
#  location_id :integer
#  event_rate  :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Event < ActiveRecord::Base

	has_many :transactions
	belongs_to :location
	belongs_to :activity
	belongs_to :host
	validates :event_rate, presence: true
	validates :host_id, presence: true
	validates :activity_id, presence: true
	validates :location_id, presence: true


	def new_location_from_event_form(new_location_params)
		# This commented-out line is only necessary to make controller tests pass...
		return false if new_location_params.nil?
		return false if new_location_params[:title].empty?
		location = Location.find_or_create_by(title: new_location_params[:title])
		self.update_attributes(location_id: location.id)
	end

	def new_activity_from_event_form(new_activity_params)
		# This commented-out line is only necessary to make controller tests pass...
		return false if new_activity_params.nil?
		return false if new_activity_params[:title].empty?
		activity = Activity.find_or_create_by(title: new_activity_params[:title])
		self.update_attributes(activity_id: activity.id)
	end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:edit, :show, :update, :confirm_delete, :destroy, :new_schedule_block, :create_schedule_block, :show_schedule_block, :edit_schedule_block, :update_schedule_block, :block_schedule_block, :confirmation_page]
  before_action :set_one_schedule_block, only: [:block_schedule_block, :edit_schedule_block, :show_schedule_block, :create_appointment]
  before_action :set_all_schedule_blocks, only: [:edit, :show, :confirm_delete]
  before_action :set_sb_service_object, only: [:create_schedule_block, :update_schedule_block]

  def index
    # from DEM branch
    @q = Event.ransack(params[:q])
    @events = @q.result
    @schedule_blocks = ScheduleBlockService.new.get_schedule_blocks if @events
  end

  def create  
    stripped_params = event_params.except(:new_location, :new_activity)
    @event = current_user.host.events.create(stripped_params)
    @event.new_location_from_event_form(event_params[:new_location])
    @event.new_activity_from_event_form(event_params[:new_activity])

    if @event.save
      redirect_to new_schedule_block_event_path(@event.id)
    else
      flash[:notice] = "Event could not be created. Please try again."
      render :new
    end

  end

  def new
    @event = Event.new
    @activity_options = Activity.all.map{|x| [x.title]}
    @activity = @event.build_activity
    @host = @event.build_host
    @location_options = Location.all.map{|x| [x.title]}
    @location = @event.build_location
  end

  def edit
  end

  def show
  end

  def update
    stripped_params = event_params.except(:new_location, :new_activity)
    @event.new_location_from_event_form(event_params[:new_location])
    @event.new_activity_from_event_form(event_params[:new_activity])

    if @event.update(stripped_params)
      flash[:notice] = "Event succesfully updated."
      redirect_to @event
    else
      flash[:notice] = "Event was not updated."
      render :edit
    end
  end

  def confirm_delete
  end

  def destroy
    @event.destroy  
    flash[:notice] = "Event succesfully deleted."
    redirect_to events_path
  end

  #========================================
  # Custom Schedule Block actions below...
  #========================================

    def index_schedule_block
      @event = Event.first
      @schedule_blocks = ScheduleBlockService.new.get_schedule_blocks
    end

    def new_schedule_block
    end

    def create_schedule_block
      stripped_params = params.except(:utf8, :authenticity_token, :commit, :controller, :action, :id)
      if @sb.create_schedule_block(stripped_params)
        redirect_to event_path(@event.id)
        flash[:notice] = "Schedule block succesfully created."
      else
        render :create_schedule_block
        flash[:notice] = "Schedule block was not created."
      end
    end

    def show_schedule_block
    end

    def edit_schedule_block
    end

    def update_schedule_block
      stripped_params = params.except(:utf8, :authenticity_token, :commit, :controller, :action, :schedule_block_id, :id)
      schedule_block_id = params[:schedule_block_id]

      if @sb.update_schedule_block(schedule_block_id, stripped_params)
        redirect_to event_path(@event.id)
        flash[:notice] = "Schedule block was succesfully updated."
      else
        render :edit_schedule_block
        flash[:error] = "Schedule block was not updated."
      end

    end

    def block_schedule_block
    end


  #========================================
  # Custom Appointment actions below...
  #========================================

  def create_appointment
    sb_id = params['schedule_block_id']
    appointment_params = params.except(:schedule_block_id, :authenticity_token, :controller, :action, :id)

    if AppointmentService.new.create_appointment(sb_id, appointment_params)
      redirect_to my_appointments_user_path
      flash[:success] = 'Appointment was succesfully created!'
    else
      render :show_schedule_block
      flash[:error] = 'Appointment was not created!'
    end
  end

  private

    def set_event
      @event = Event.find(params[:id])
    end

    def event_params
      params.require(:event).permit(:event_rate, :location_id, {new_location: [:title]}, :activity_id, {new_activity: [:title]}, :host_id)
    end

    def set_one_schedule_block
      @schedule_block = ScheduleBlockService.new.get_schedule_block(params[:sb_id])
    end

    def set_all_schedule_blocks
      @schedule_blocks = ScheduleBlockService.new.get_schedule_blocks.select{|sb| sb['event_id'] == @event.id }
    end

    def set_sb_service_object
      @sb = ScheduleBlockService.new
    end


end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_access_denied.html.erb
<h1>Access Denied</h1>

<h3>You do not have access to this page. Bitch.</h3>

app/views/events/_customer_show.html.erb
<h3>Please review the event details below.</h3>

<div class="row">
  <div class="col-md-12">
    <table class="table table-hover table-bordered table-striped">
      <thead>
        <tr>
          <th>Title</th>
          <th>Location</th>
          <th>Time</th>
          <th>Host</th>
          <th>Status</th>
          <th>Price</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td><%= @event.activity.title %></td>
          <td><%= @event.location.title %></td>
          <td><%= DateTime.parse(@schedule_block['start_time']).strftime("%l:%M %p, %A, %B %e, %Y")%>-<%= DateTime.parse(@schedule_block['end_time']).strftime("%l:%M %p, %A, %B %e, %Y") %></td>
          <td><%= @event.host.user.first_name %></td>
          <td><%= @schedule_block['status'] %></td>
          <td><%= "$#{@event.rate}" %></td>
        </tr>
      </tbody>
    </table>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <%= link_to "Back to All Events", events_path, class: 'btn btn-default'  %>
  </div>
</div>

app/views/events/_host_show.html.erb
<h3>Please review the event details below.</h3>

<div class="row">
  <div class="col-md-12">
    <table class="table table-hover table-bordered table-striped">
      <thead>
        <tr>
          <th>Title</th>
          <th>Location</th>
          <th>Time</th>
          <th>Host</th>
          <th>Status</th>
          <th>Price</th>
          <th>Reservation Min</th>
          <th>Reservation Max</th>
          <% end %>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td><%= @event.activity.title %></td>
          <td><%= @event.location.title %></td>
          <td><%= DateTime.parse(@schedule_block['start_time']).strftime("%l:%M %p, %A, %B %e, %Y")%>-<%= DateTime.parse(@schedule_block['end_time']).strftime("%l:%M %p, %A, %B %e, %Y") %></td>
          <td><%= @event.host.user.first_name %></td>
          <td><%= @schedule_block['status'] %></td>
          <td><%= "$#{@event.rate}" %></td>
          <td><%= @schedule_block['reservation_min'] %></td>
          <td><%= @schedule_block['reservation_max'] %></td>
          <td><%= link_to 'Edit', edit_event_path(@event.id, schedule_block_ID: @schedule_block['id']) %></td>
          <td><%= link_to 'Delete', delete_event_path(@event.id, schedule_block_ID: @schedule_block['id']) %></td>
        </tr>
      </tbody>
    </table>
  </div>
</div>



<div class="row">
  <div class="col-md-12">
    <%= link_to "Edit Event", edit_event_path(@event.id), class: 'btn btn-default'  %>
    <%= link_to "Create New Event", new_event_path, class: 'btn btn-default' %>
    <%= link_to "All Events", events_path, class: 'btn btn-default'  %>
  </div>
</div>

app/views/events/block_schedule_block.html.erb
<% if current_user.host? %>
  <%= render 'events/host_views/block_schedule_block' %>
<% else %>
  <%= render 'access_denied' %>
<% end %>

app/views/events/cancel_schedule_block.html.erb
<h1>Cancel Event Instance</h1>

<!-- If schedule_block has appointments, display message stating the Host cannot cancel appointment
-->

<h3>Are you sure you want to cancel this Event Instance?</h3>

<div class="row">
  <div class="col-md-12">
    <table class="table table-hover table-bordered table-striped">
      <thead>
        <tr>
          <th>Date</th>
          <th>Time</th>
          <th>Attendees</th>
          <th>Reservation Min</th>
          <th>Reservation Max</th>
          <th>Status</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td><%= DateTime.parse(@schedule_block['start_time']).strftime("%a, %B %e, %Y") %></td>
          <td><%= DateTime.parse(@schedule_block['start_time']).strftime("%l:%M")%>-<%= DateTime.parse(@schedule_block['end_time']).strftime("%l:%M %p") %></td>
          <td>NUMBER OF APPTS HERE</td>
          <td><%= @schedule_block['reservation_min'] %></td>
          <td><%= @schedule_block['reservation_max'] %></td>
          <td><%= @schedule_block['status'] %></td>
        </tr>
      </tbody>
    </table>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
  <%= button_to 'Cancel Event Instance', update_schedule_block_event_path, params: {schedule_block_id: @schedule_block['id'], status: 'cancelled' }, class: 'btn btn-danger' %>
  </div>
</div>

app/views/events/confirm_delete.html.erb
<% if current_user.host? %>
  <%= render 'events/host_views/confirm_delete' %>
<% else %>
  <%= render 'access_denied' %>
<% end %>

app/views/events/delete.html.erb
<div class="col-md-8 col-md-offset-2">
<div class="row">
  <h1>Delete Event</h1>
</div>

<div class="row">
  <h3>Are you sure you want to delete the following event?</h3>
</div>

<div class="row">
  <table class="table table-hover table-bordered table-striped">
    <thead>
      <tr>
        <th>Title</th>
        <th>Location</th>
        <th>Host</th>
        <th>Price</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td><%= @event.activity.title %></td>
        <td><%= @event.location.title %></td>
        <td><%= @event.host_id %></td>
        <td><%= @event.rate %></td>
      </tr>
    </tbody>
  </table>
</div>

<div class="row">
  <h3>This will delete all the following event instances:</h3>
</div>

<div class="row">
  <table class="table table-hover table-bordered table-striped">
    <thead>
      <tr>
        <th>Date</th>
        <th>Time</th>
        <th>Reservation Min</th>
        <th>Reservation Max</th>
        <th>Status</th>
      </tr>
    </thead>
    <tbody>
      <% @schedule_blocks.each do |sb| %>
      <td><%= "#{DateTime.parse(sb['start_time']).strftime("%a, %B %e, %Y")}" %></td>
      <td><%= "#{DateTime.parse(sb['start_time']).strftime("%l:%M %p")} - #{DateTime.parse(sb['end_time']).strftime("%l:%M %p")}" %></td>
      <td><%= sb['reservation_min'] %></td>
      <td><%= sb['reservation_max'] %></td>
      <td><%= sb['status'] %></td>
      <% end %>
    </tbody>
  </table>
</div>

<div class="row">
  <%= link_to 'Delete Event', event_path(@event.id), method: :delete, class: 'btn btn-danger' %>
  <br/>
  <br/>
  <%= link_to "Edit Event", edit_event_path(@event.id), class: 'btn btn-default' %>
  <%= link_to "Create New Event", new_event_path, class: 'btn btn-default' %>
  <%= link_to "All Events", events_path, class: 'btn btn-default' %>
</div>

app/views/events/edit.html.erb
<% if current_user.host? %>
  <%= render 'events/host_views/edit' %>
<% else %>
  <%= render 'access_denied' %>
<% end %>

app/views/events/edit_schedule_block.html.erb
<% if current_user.host? %>
  <%= render 'events/host_views/edit_schedule_block' %>
<% else %>
  <%= render 'access_denied' %>
<% end %>

app/views/events/index.html.erb
<% if current_user.host? %>
  <%= render 'events/host_views/index' %>
<% else %>
  <%= render 'events/customer_views/index' %>
<% end %>

app/views/events/index_schedule_block.html.erb
<% if current_user.host? %>
  <%= render 'events/host_views/index_schedule_block' %>
<% else %>
  <%= render 'access_denied' %>
<% end %>

app/views/events/new.html.erb
<% if current_user.host? %>
  <%= render 'events/host_views/new' %>
<% else %>
  <%= render 'access_denied' %>
<% end %>

app/views/events/new_schedule_block.html.erb
<% if current_user.host? %>
  <%= render 'events/host_views/new_schedule_block' %>
<% else %>
  <%= render 'access_denied' %>
<% end %>

app/views/events/show.html.erb
<% if current_user.host? %>
  <%= render 'events/host_views/show' %>
<% else %>
  <%= render 'events/customer_views/show' %>
<% end %>