config/routes.rb
Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  root to: 'visitors#index'
  devise_for :users
  resources :hosts, :activities, :locations
  resources :users do
    member do 
      get 'my_appointments'
    end
  end
  resources :events do 
    member do
      get 'confirm_delete'
      get 'new_schedule_block'
      post 'create_schedule_block'
      get 'show_schedule_block'
      get 'edit_schedule_block'
      post 'update_schedule_block'
      get 'block_schedule_block'
      post 'create_appointment'
    end
    collection do
      get 'index_schedule_block'
    end
  end

end

app/models/event.rb
# == Schema Information
#
# Table name: events
#
#  id          :integer          not null, primary key
#  activity_id :integer
#  host_id     :integer
#  location_id :integer
#  event_rate  :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Event < ActiveRecord::Base

	has_many :transactions
	belongs_to :location
	belongs_to :activity
	belongs_to :host
	validates :event_rate, presence: true
	validates :host_id, presence: true
	validates :activity_id, presence: true
	validates :location_id, presence: true


	def new_location_from_event_form(new_location_params)
		# This commented-out line is only necessary to make controller tests pass...
		return false if new_location_params.nil?
		return false if new_location_params[:title].empty?
		location = Location.find_or_create_by(title: new_location_params[:title])
		self.update_attributes(location_id: location.id)
	end

	def new_activity_from_event_form(new_activity_params)
		# This commented-out line is only necessary to make controller tests pass...
		return false if new_activity_params.nil?
		return false if new_activity_params[:title].empty?
		activity = Activity.find_or_create_by(title: new_activity_params[:title])
		self.update_attributes(activity_id: activity.id)
	end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:edit, :show, :update, :confirm_delete, :destroy, :new_schedule_block, :create_schedule_block, :show_schedule_block, :edit_schedule_block, :update_schedule_block, :block_schedule_block, :confirmation_page]
  before_action :set_one_schedule_block, only: [:block_schedule_block, :edit_schedule_block, :show_schedule_block, :create_appointment]
  before_action :set_all_schedule_blocks, only: [:edit, :show, :confirm_delete]
  before_action :set_sb_service_object, only: [:create_schedule_block, :update_schedule_block]

  def index
    # from DEM branch
    @q = Event.ransack(params[:q])
    @events = @q.result
    @schedule_blocks = ScheduleBlockService.new.get_schedule_blocks if @events
  end

  def create  
    stripped_params = event_params.except(:new_location, :new_activity)
    @event = current_user.host.events.create(stripped_params)
    @event.new_location_from_event_form(event_params[:new_location])
    @event.new_activity_from_event_form(event_params[:new_activity])

    if @event.save
      redirect_to new_schedule_block_event_path(@event.id)
    else
      flash[:notice] = "Event could not be created. Please try again."
      render :new
    end

  end

  def new
    @event = Event.new
    @activity_options = Activity.all.map{|x| [x.title]}
    @activity = @event.build_activity
    @host = @event.build_host
    @location_options = Location.all.map{|x| [x.title]}
    @location = @event.build_location
  end

  def edit
  end

  def show
  end

  def update
    stripped_params = event_params.except(:new_location, :new_activity)
    @event.new_location_from_event_form(event_params[:new_location])
    @event.new_activity_from_event_form(event_params[:new_activity])

    if @event.update(stripped_params)
      flash[:notice] = "Event succesfully updated."
      redirect_to @event
    else
      flash[:notice] = "Event was not updated."
      render :edit
    end
  end

  def confirm_delete
  end

  def destroy
    @event.destroy  
    flash[:notice] = "Event succesfully deleted."
    redirect_to events_path
  end

  #========================================
  # Custom Schedule Block actions below...
  #========================================

    def index_schedule_block
      @event = Event.first
      @schedule_blocks = ScheduleBlockService.new.get_schedule_blocks
    end

    def new_schedule_block
    end

    def create_schedule_block
      stripped_params = params.except(:utf8, :authenticity_token, :commit, :controller, :action, :id)
      if @sb.create_schedule_block(stripped_params)
        redirect_to event_path(@event.id)
        flash[:notice] = "Schedule block succesfully created."
      else
        render :create_schedule_block
        flash[:notice] = "Schedule block was not created."
      end
    end

    def show_schedule_block
    end

    def edit_schedule_block
    end

    def update_schedule_block
      stripped_params = params.except(:utf8, :authenticity_token, :commit, :controller, :action, :schedule_block_id, :id)
      schedule_block_id = params[:schedule_block_id]

      if @sb.update_schedule_block(schedule_block_id, stripped_params)
        redirect_to event_path(@event.id)
        flash[:notice] = "Schedule block was succesfully updated."
      else
        render :edit_schedule_block
        flash[:error] = "Schedule block was not updated."
      end

    end

    def block_schedule_block
    end


  #========================================
  # Custom Appointment actions below...
  #========================================

  def create_appointment
    sb_id = params['schedule_block_id']
    appointment_params = params.except(:schedule_block_id, :authenticity_token, :controller, :action, :id)

    if AppointmentService.new.create_appointment(sb_id, appointment_params)
      redirect_to my_appointments_user_path
      flash[:success] = 'Appointment was succesfully created!'
    else
      render :show_schedule_block
      flash[:error] = 'Appointment was not created!'
    end
  end

  private

    def set_event
      @event = Event.find(params[:id])
    end

    def event_params
      params.require(:event).permit(:event_rate, :location_id, {new_location: [:title]}, :activity_id, {new_activity: [:title]}, :host_id)
    end

    def set_one_schedule_block
      @schedule_block = ScheduleBlockService.new.get_schedule_block(params[:sb_id])
    end

    def set_all_schedule_blocks
      @schedule_blocks = ScheduleBlockService.new.get_schedule_blocks.select{|sb| sb['event_id'] == @event.id }
    end

    def set_sb_service_object
      @sb = ScheduleBlockService.new
    end


end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/host_views/_block_schedule_block.html.erb
<h1>Block Event Instance</h1>

<!-- If schedule_block has appointments, display message stating the Host cannot cancel appointment
-->

<% if @schedule_block['status'] == 'blocked' %>
  <h3>Are you sure you want to <b><u>unblock</u></b> this Event Instance?</h3>
<% else %>
  <h3>Are you sure you want to <b><u>block</u></b> this Event Instance?</h3>
<% end %>

<div class="row">
  <div class="col-md-12">
    <table class="table table-hover table-bordered table-striped">
      <thead>
        <tr>
          <th>Date</th>
          <th>Time</th>
          <th>Attendees</th>
          <th>Reservation Min</th>
          <th>Reservation Max</th>
          <th>Status</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td><%= DateTime.parse(@schedule_block['start_time']).strftime("%a, %B %e, %Y") %></td>
          <td><%= DateTime.parse(@schedule_block['start_time']).strftime("%l:%M")%>-<%= DateTime.parse(@schedule_block['end_time']).strftime("%l:%M %p") %></td>
          <td>NUMBER OF APPTS HERE</td>
          <td><%= @schedule_block['reservation_min'] %></td>
          <td><%= @schedule_block['reservation_max'] %></td>
          <td><%= @schedule_block['status'] %></td>
        </tr>
      </tbody>
    </table>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <% if @schedule_block['status'] == 'blocked' %>
      <%= button_to 'Unblock Event Instance', update_schedule_block_event_path, params: {schedule_block_id: @schedule_block['id'], status: 'open' }, class: 'btn btn-danger' %>
    <% else %>
     <%= button_to 'Block Event Instance', update_schedule_block_event_path, params: {schedule_block_id: @schedule_block['id'], status: 'blocked' }, class: 'btn btn-danger' %>
    <% end %>
  </div>
</div>

app/views/events/host_views/_confirm_delete.erb
<div class="col-md-8 col-md-offset-2">
<div class="row">
  <h1>Delete Event</h1>
</div>

<div class="row">
  <h3>Are you sure you want to delete the following event?</h3>
</div>

<div class="row">
  <table class="table table-hover table-bordered table-striped">
    <thead>
      <tr>
        <th>Activity</th>
        <th>Location</th>
        <th>Host</th>
        <th>Price</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td><%= @event.activity.title %></td>
        <td><%= @event.location.title %></td>
        <td><%= @event.host_id %></td>
        <td><%= @event.event_rate %></td>
      </tr>
    </tbody>
  </table>
</div>

<% if @schedule_blocks %>
  <div class="row">
    <h3>This will delete all the following event instances:</h3>
  </div>

  <div class="row">
    <table class="table table-hover table-bordered table-striped">
      <thead>
        <tr>
          <th>Date</th>
          <th>Time</th>
          <th>Reservation Min</th>
          <th>Reservation Max</th>
          <th>Status</th>
        </tr>
      </thead>
      <tbody>
        <% @schedule_blocks.each do |sb| %>
        <tr>
          <td><%= "#{DateTime.parse(sb['start_time']).strftime("%a, %B %e, %Y")}" %></td>
          <td><%= "#{DateTime.parse(sb['start_time']).strftime("%l:%M %p")} - #{DateTime.parse(sb['end_time']).strftime("%l:%M %p")}" %></td>
          <td><%= sb['reservation_min'] %></td>
          <td><%= sb['reservation_max'] %></td>
          <td><%= sb['status'] %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
<% end %>

<div class="row">
  <%= link_to 'Delete Event', event_path(@event.id), method: :delete, class: 'btn btn-danger' %>
  <br/>
  <br/>
  <%= link_to "Edit Event", edit_event_path(@event.id), class: 'btn btn-default' %>
  <%= link_to "Create New Event", new_event_path, class: 'btn btn-default' %>
  <%= link_to "All Events", events_path, class: 'btn btn-default' %>
</div>

app/views/events/host_views/_edit.html.erb
<div class="col-md-10 col-md-offset-1">

<div class="row">
    <h1>Update Event</h1>
</div>

<div class="row">
  <h4>Warning: Any changes you make to this event will affect all the following Event Instances</h4>
  <table class="table table-hover table-bordered table-striped">
    <thead>
      <tr>
        <th>Date</th>
        <th>Start Time</th>
        <th>End Time</th>
        <th>Reservation Min</th>
        <th>Reservation Max</th>
        <th>Status</th>
      </tr>
    </thead>
    <tbody>
      <% @schedule_blocks.each do |sb| %>
      <tr>
        <td><%= DateTime.parse(sb['start_time']).strftime("%A, %B %-d, %Y") %></td>
        <td><%= DateTime.parse(sb['start_time']).strftime("%l:%M %P") %></td>
        <td><%= DateTime.parse(sb['end_time']).strftime("%l:%M %P") %></td>
        <td><%= sb['reservation_min'] %></td>
        <td><%= sb['reservation_max'] %></td>
        <td><%= sb['status'] %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

<div class="row">
  <div class="col-md-8 col-md-offset-2">
  <%= bootstrap_form_for @event do |f| %>
    <%= f.collection_select :activity_id, Activity.all, :id, :title, prompt: "Select Activity" %>
    <%= f.fields_for :new_activity do |new_activity| %>
        <%= new_activity.text_field :title, label: 'or create a new activity: ', placeholder: 'Only use to create a new activity that is not listed above' %>
    <% end %>
    <%= f.collection_select :location_id, Location.all, :id, :title, prompt: "Select Location" %>
    <%= f.fields_for :new_location do |new_location| %>
        <%= new_location.text_field :title, label: 'or create a new location: ', placeholder: 'Only use to create a new location that is not listed above' %>
    <% end %>
    <%= f.number_field :event_rate, placeholder: 'Price in US dollars' %>

    <%= hidden_field_tag :host, value = current_user.host %>
    <%= hidden_field_tag :schedule_block_ID %>
    <%= f.submit 'Update Event' %>
  <% end %>
</div>
</div>

<div class="row">
  <br/>
  <%= link_to 'All Events', events_path, class: 'btn btn-default' %>
  <%= link_to 'Create New Event', new_event_path, class: 'btn btn-default' %>
</div>

</div>

app/views/events/host_views/_edit_schedule_block.html.erb
<h1>Edit Schedule Block</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <h1>Create a New Event Instance</h1>
  </div>
</div>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <h3><%= "#{@event.activity.title} at #{@event.location.title}" %></h3>
    <br/>
  </div>
</div>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= bootstrap_form_tag url: "/events/#{@event.id}/update_schedule_block" do |f| %>
      <%= f.datetime_select :start_time, ampm:true, default: DateTime.parse(@schedule_block['start_time']) %>
      <%= f.datetime_select :end_time, ampm:true, default: DateTime.parse(@schedule_block['end_time']) %>
      <%= f.number_field :reservation_min, value: @schedule_block['reservation_min'].to_i %>
      <%= f.number_field :reservation_max, value: @schedule_block['reservation_max'].to_i %>
      <%= hidden_field_tag :host_id, value = current_user.host.id %>
      <%= hidden_field_tag :event_id, value =  @event.id %>
      <%= hidden_field_tag :location_id, value = @event.location.id %>
      <%= hidden_field_tag :status, value = 'open' %>
      <%= hidden_field_tag :schedule_block_id, value = @schedule_block['id'] %>
      
      <%= f.submit 'Update Event Instance' %>
    <% end %>
  </div>
</div>

app/views/events/host_views/_index.html.erb
<div class="row">
  <div class="col-md-3">
    <h1>Events</h1>
  </div>
  <div class="col-md-3 col-md-offset-6">
    <br/>
    <%= link_to 'Create New Event', new_event_path, class: 'btn btn-primary pull-right' %>
  </div>
</div>

<div class="row">
  <%= search_form_for @q do |f| %>
    <%= f.label :activity_title_cont %>
    <%= f.search_field :activity_title_cont %>

    <%= f.submit %>

  <% end %>
</div>

<div class="row">
  <table class="table table-hover table-bordered">
    <thead>
      <tr>
        <th>Activity</th>
        <th>Location</th>
        <th>Price</th>
        <th>Event Instances</th>
      </tr>
    </thead>
    <tbody>
      <% @events.each do |event| %>
        <% schedule_block_array = @schedule_blocks.select{|sb| sb['event_id'] == event.id} %>
        <tr>
          <td><h4><%= link_to "#{event.activity.title}", event_path(event.id) %></h4></td>
          <td><h4><%= event.location.title %></h4></td>
          <td><h4><%= "$#{event.event_rate}" %></h4></td>
          <td><ul>
            <% schedule_block_array.each do |sb| %>
              <li><b>
              <%= DateTime.parse(sb['start_time']).strftime('%a, %B %e, %Y') %>
              <%= DateTime.parse(sb['start_time']).strftime('%l:%M') %>
              <%= DateTime.parse(sb['end_time']).strftime('%l:%M %p') %>
              </b>
              <%= link_to 'View', show_schedule_block_event_path(id: event.id, sb_id: sb['id']) %>
              </li>
            <% end %>
          </ul>
          </td>
          <td><%= link_to 'Create a new Event Instance', new_schedule_block_event_path(event.id), class: 'btn btn-default btn-sm btn-block' %><br/>
          <%= link_to 'Event Instance Details', event_path(event.id), class: 'btn btn-default btn-sm btn-block' %><br/>
          <%= link_to 'Edit Event', edit_event_path(event.id), class: 'btn btn-default btn-sm btn-block' %><br/>
          <%= link_to 'Delete Event', confirm_delete_event_path(event.id), class: 'btn btn-default btn-sm btn-block' %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/events/host_views/_index_schedule_block.html.erb
<h1>All Event Instances</h1>

<div class="row">
  <div class="col-md-12">
    <table class="table table-hover table-bordered table-striped">
      <thead>
        <tr>
          <th>Activity</th>
          <th>Rate</th>
          <th>Host</th>
          <th>Location</th>
          <th>Date</th>
          <th>Time</th>
          <th>Attendees</th>
          <th>Reservation Min</th>
          <th>Reservation Max</th>
          <th>Status</th>
        </tr>
      </thead>
      <tbody>
        <% @schedule_blocks.each do |sb| %>
          <% event = Event.find(sb['event_id']) %>
        <tr>
          <td><%= event.activity.title %></td>
          <td>$<%= event.event_rate %></td>
          <td><%= event.host.user.first_name %></td>
          <td><%= event.location.title %></td>
          <td><%= DateTime.parse(sb['start_time']).strftime("%a, %B %e, %Y") %></td>
          <td><%= DateTime.parse(sb['start_time']).strftime("%l:%M")%>-<%= DateTime.parse(sb['end_time']).strftime("%l:%M %p") %></td>
          <td>NUMBER OF APPTS HERE</td>
          <td><%= sb['reservation_min'] %></td>
          <td><%= sb['reservation_max'] %></td>
          <td><%= sb['status'] %></td>
          <td><%= link_to 'Edit', edit_schedule_block_event_path(id: @event.id, sb_id: sb['id']) %></td>
          <td><%= link_to 'Cancel', cancel_schedule_block_event_path(id: @event.id, sb_id: sb['id'])%></td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/events/host_views/_new.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <h1>Create a New Event</h1>
  </div>
</div>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <% if current_user.host %>
      <%= bootstrap_form_for @event, label_errors: true do |f| %>
        <%= f.collection_select :activity_id, Activity.all, :id, :title, prompt: "Select Activity" %>
        <%= f.fields_for :new_activity do |new_activity| %>
            <%= new_activity.text_field :title, label: 'or create a new activity: ', placeholder: 'Only use to create a new activity that is not listed above' %>
        <% end %>
        <%= f.collection_select :location_id, Location.all, :id, :title, prompt: "Select Location" %>
        <%= f.fields_for :new_location do |new_location| %>
            <%= new_location.text_field :title, label: 'or create a new location: ', placeholder: 'Only use to create a new location that is not listed above' %>
        <% end %>
        <%= f.number_field :event_rate, placeholder: 'Price in US dollars' %>
        <%= hidden_field_tag :host, value = current_user.host %>
        <%= f.submit 'Create Event', class: 'btn btn-primary' %>
      <% end %>
    <% else %>
      <h2>You cannot create an event, you are not a host!</h2>
    <% end %>
  </div>
</div>
<br/>

app/views/events/host_views/_new_schedule_block.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <h1>Create a New Event Instance</h1>
  </div>
</div>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <h3><%= "#{@event.activity.title} at #{@event.location.title}" %></h3>
    <br/>
  </div>
</div>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= bootstrap_form_tag url: "/events/#{@event.id}/create_schedule_block" do |f| %>
      <%= f.datetime_select :start_time, ampm:true %>
      <%= f.datetime_select :end_time, ampm:true %>
      <%= f.number_field :reservation_min %>
      <%= f.number_field :reservation_max %>
      <%= hidden_field_tag :host_id, value = current_user.host.id %>
      <%= hidden_field_tag :event_id, value = @event.id %>
      <%= hidden_field_tag :location_id, value = @event.location.id %>
      <%= hidden_field_tag :status, value = 'open' %>
      
      <%= f.submit 'Create Event Instance', class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>

app/views/events/host_views/_show.html.erb
<h1><%= "#{@event.activity.title} at #{@event.location.title}" %></h1>

<div class="row">
  <div class="col-md-12">
    <h2>Event Details</h2>
    <table class="table table-hover table-bordered table-striped">
      <thead>
        <tr>
          <th>Activity</th>
          <th>Rate</th>
          <th>Host</th>
          <th>Location</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td><%= @event.activity.title %></td>
          <td>$<%= @event.event_rate %></td>
          <td><%= @event.host.user.first_name %></td>
          <td><%= @event.location.title %></td>
        </tr>
      </tbody>
    </table>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <%= link_to 'Edit Event', edit_event_path(@event.id), class: 'btn btn-primary' %>
    <%= link_to 'Delete Event', confirm_delete_event_path(@event.id), class: 'btn btn-danger' %>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <h2>Event Instances</h2>
    <table class="table table-hover table-bordered table-striped">
      <thead>
        <tr>
          <th>Date</th>
          <th>Time</th>
          <th>Attendees</th>
          <th>Reservation Min</th>
          <th>Reservation Max</th>
          <th>Status</th>
        </tr>
      </thead>
      <tbody>
        <% @schedule_blocks.each do |sb| %>
        <tr>
          <td><%= DateTime.parse(sb['start_time']).strftime("%a, %B %e, %Y") %></td>
          <td><%= DateTime.parse(sb['start_time']).strftime("%l:%M")%>-<%= DateTime.parse(sb['end_time']).strftime("%l:%M %p") %></td>
          <td>NUMBER OF APPTS HERE</td>
          <td><%= sb['reservation_min'] %></td>
          <td><%= sb['reservation_max'] %></td>
          <td><%= sb['status'] %></td>
          <td><%= link_to 'Edit', edit_schedule_block_event_path(id: @event.id, sb_id: sb['id']) %></td>
          <td><% if sb['status'] == 'blocked' %>
                <%= link_to 'Unblock', block_schedule_block_event_path(id: @event.id, sb_id: sb['id'])%>
              <% else %>
                <%= link_to 'Block', block_schedule_block_event_path(id: @event.id, sb_id: sb['id'])%></td>
              <% end %>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>


<div class="row">
  <div class="col-md-12">
    <%= link_to 'Create New Event Instance', new_schedule_block_event_path(@event.id), class: 'btn btn-primary' %>
  </div>
</div>

app/views/events/host_views/_show_schedule_block.html.erb
<h1><%= "#{@event.activity.title} at #{@event.location.title}" %></h1>

<div class="row">
  <div class="col-md-12">
    <h2>Event Details</h2>
    <table class="table table-hover table-bordered table-striped">
      <thead>
        <tr>
          <th>Activity</th>
          <th>Rate</th>
          <th>Host</th>
          <th>Location</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td><%= @event.activity.title %></td>
          <td>$<%= @event.event_rate %></td>
          <td><%= @event.host.user.first_name %></td>
          <td><%= @event.location.title %></td>
        </tr>
      </tbody>
    </table>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <h2>Event Instance</h2>
    <table class="table table-hover table-bordered table-striped">
      <thead>
        <tr>
          <th>Date</th>
          <th>Time</th>
          <th>Attendees</th>
          <th>Reservation Min</th>
          <th>Reservation Max</th>
          <th>Status</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td><%= DateTime.parse(@schedule_block['start_time']).strftime("%a, %B %e, %Y") %></td>
          <td><%= DateTime.parse(@schedule_block['start_time']).strftime("%l:%M")%>-<%= DateTime.parse(@schedule_block['end_time']).strftime("%l:%M %p") %></td>
          <td>NUMBER OF APPTS HERE</td>
          <td><%= @schedule_block['reservation_min'] %></td>
          <td><%= @schedule_block['reservation_max'] %></td>
          <td><%= @schedule_block['status'] %></td>
          <td><%= link_to 'Edit', edit_schedule_block_event_path(id: @event.id, sb_id: @schedule_block['id']) %></td>
          <td><%= link_to 'Cancel', block_schedule_block_event_path(id: @event.id, sb_id: @schedule_block['id'])%></td>
        </tr>
      </tbody>
    </table>
  </div>
</div>


<div class="row">
  <div class="col-md-12">
    <%= link_to 'All Event Instances for this Event', event_path(@event.id), class: 'btn btn-primary' %>
    <%= link_to 'Index of All Event Instances', index_schedule_block_events_path, class: 'btn btn-default' %>
  </div>
</div>