config/routes.rb
Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  root to: 'visitors#index'
  devise_for :users
  resources :hosts, :activities, :locations
  resources :users do
    member do 
      get 'my_appointments'
    end
  end
  resources :events do 
    member do
      get 'confirm_delete'
      get 'new_schedule_block'
      post 'create_schedule_block'
      get 'show_schedule_block'
      get 'edit_schedule_block'
      post 'update_schedule_block'
      get 'block_schedule_block'
      post 'create_appointment'
    end
    collection do
      get 'index_schedule_block'
    end
  end

end

app/models/activity.rb
# == Schema Information
#
# Table name: activities
#
#  id         :integer          not null, primary key
#  title      :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Activity < ActiveRecord::Base
	has_many :events
	has_many :hosts, through: :events
	has_many :locations, through: :events

	validates :title, presence: true

  acts_as_taggable # Alias for acts_as_taggable_on :tags
  acts_as_taggable_on :tags, :genres, :subjects, :trip_type
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_action :set_activity, :only => [:edit, :show, :update, :destroy]

  def index
    @activities = Activity.all
  end

  def show
  end

  def new
    @activity = Activity.new
  end

  def edit
  end

  def create
    @activity = Activity.create(activity_params)
    @activity.tag_list.add(activity_params[:tag_list], parse: true)

    if @activity.save
      redirect_to @activity
    else
      render :new
    end
  end
  
  def update
    if @activity.update(activity_params)
      redirect_to activity_path(@activity)
    else
      render :edit
    end
  end

  def destroy
    @activity.destroy
    redirect_to activities_path
  end

  private

    def set_activity
      @activity = Activity.find(params[:id])
    end

    def activity_params
      params.require(:activity).permit(:title, :tag_list)
    end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/views/activities/edit.html.erb
<h1>Edit Activity</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <h1>New Activity</h1>
  </div>
</div>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= bootstrap_form_for @activity do |f| %>
      <%= f.text_field :title %>
      <%= f.text_field :tag_list %>
      <%= f.submit 'Update Activity' %>
    <% end %>
  </div>
</div>
<br/>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= link_to 'All Activities', activities_path, class: 'btn btn-default' %>
    <%= link_to 'Create New Activity', new_activity_path, class: 'btn btn-default' %>
  </div>
</div>

app/views/activities/index.html.erb
<div class="row">
  <div class="col-md-3">
    <h1>Activities</h1>
  </div>
  <div class="col-md-3 col-md-offset-6">
    <br/>
    <%= link_to 'Create New Activity', new_activity_path, class: 'btn btn-default pull-right' %>
  </div>
</div>


<div class="row">
  <table class="table table-hover table-bordered table-striped">
    <thead>
      <tr>
        <th>Title</th>
        <th>Tags</th>
      </tr>
    </thead>

    <tbody>
      <% @activities.each do |activity| %>
      <tr>
          <td><%= activity.title %></td>
          <td><% activity.tags.each_with_index do |tag, index| %>
                <% if index == activity.tags.size - 1 %>
                  <%= "#{tag.name}" %>
                <% else %>
                  <%= "#{tag.name}, " %>
                <% end %>
              <% end %>
          </td>
          <td><%= link_to 'Edit', edit_activity_path(activity.id) %></td>
          <td><%= link_to 'Delete', activity_path(activity.id), method: :delete %></td>
      </tr>
      <% end %>
    </tbody>
  </table>

<%= link_to 'Create New Activity', new_activity_path, class: 'btn btn-default' %>

app/views/activities/new.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <h1>New Activity</h1>
  </div>
</div>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= bootstrap_form_for @activity do |f| %>
      <%= f.text_field :title %>
      <%= f.text_field :tag_list %>
      <%= f.submit 'Create Activity' %>
    <% end %>
  </div>
</div>
<br/>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= link_to 'All Activities', activities_path, class: 'btn btn-default' %>
  </div>
</div>

app/views/activities/show.html.erb
<h1>Activity</h1>

<div class="row">
  <div class="col-md-12">
    <table class="table table-hover table-bordered table-striped">
      <thead>
        <tr>
          <th>Title</th>
          <th>Tags</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td><%= @activity.title %></td>
          <td><% @activity.tags.each_with_index do |tag, index| %>
                <% if index == @activity.tags.size - 1 %>
                  <%= "#{tag.name}" %>
                <% else %>
                  <%= "#{tag.name}, " %>
                <% end %>
              <% end %>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <%= link_to 'Edit Activity', edit_activity_path(@activity.id), class: 'btn btn-default' %>
    <%= link_to 'Create New Activity', new_activity_path, class: 'btn btn-default' %>
    <%= link_to 'All Activities', activities_path, class: 'btn btn-default' %>
  </div>
</div>